% my_loc_task - defining ROIs
% my_crit_task - effect estimation

% diff from 20201107 - "3runs" version of SWNloc

function [] = mega_mROI_EventsOrig_20201107b(index)
% adapted for slurm
% index - indicates which localizer/critical task combo to use
% index - possible values are 1 through 4

date = '20201107';

% localizers - MD, lang
parcels = {'MDparcels','langparcels'};
parcel_files = {
    '/mindhive/evlab/u/Shared/ROIS_Nov2020/Func_MD_LHRH_HE197/MDfuncparcels_Apr2017.img',...
    '/mindhive/evlab/u/Shared/ROIS_Nov2020/Func_Lang_LH_SN220/LangParcels_n220_LH.img'};
% parcel_files = {'/mindhive/evlab/u/annaiv/Parcels/MDfuncparcels_Apr2017.img',...
%     '/mindhive/evlab/u/annaiv/Parcels/LangParcels_n220_LH.img'};

loc_tasks = {'SWNlocIPS168_3runs', 'SWNlocIPS168_3runs'};
loc_contrasts = {'N-S','S-N'};

% critical tasks - lang, EventsOrig
crit_tasks = {'SWNlocIPS168_3runs', 'EventsOrig_instrsep_2runs'};
crit_contrasts = {{'S', 'N'}, {'Sem_photo' 'Perc_photo' 'Sem_sent' 'Perc_sent' 'Sem-Perc' 'Perc-Sem' 'photo-sent' 'sent-photo'}};

% determine which loc/crit task combo to run. works for a 2x2 design 
i = floor((index-1)/2)+1;
j = mod(index+1,2)+1;

% set the loc task params
my_loc_task = loc_tasks{i}
my_loc_contrast = loc_contrasts{i};
parcel = parcels{i};
parcel_file = parcel_files{i};
    
% set the crit task params
my_crit_task = crit_tasks{j}
my_crit_contrast = crit_contrasts{j};

experiments=struct(...
    'name', my_crit_task, ...
    'pwd1','/mindhive/evlab/u/Shared/SUBJECTS/',...
    'pwd2_loc', ['firstlevel_' my_loc_task],...
    'pwd2_main', ['firstlevel_' my_crit_task],...
    'data', {{'040_KAN_langevents_01_PL2017',...
    '057_KAN_langevents_02_PL2017',...
    '059_KAN_langevents_04_PL2017',...
    '056_KAN_langevents_05_PL2017',...
    '067_KAN_langevents_06_PL2017',...
    '068_KAN_langevents_07_PL2017',...
    '019_KAN_langevents_08_PL2017',...
    '069_KAN_langevents_10_PL2017',...
    '070_KAN_langevents_11_PL2017',...
    '087_KAN_langevents_12_PL2017',...
    '078_KAN_langevents_13_PL2017',...
    '088_KAN_langevents_14_PL2017',...
    '089_KAN_langevents_15_PL2017',...
    '076_KAN_langevents_16_PL2017'}});

spmfiles_loc={};
spmfiles_main={};
for nsub=1:length(experiments.data)
    spmfiles_loc{nsub}=fullfile(experiments.pwd1,experiments.data{nsub},experiments.pwd2_loc,'SPM.mat');
    spmfiles_main{nsub}=fullfile(experiments.pwd1,experiments.data{nsub},experiments.pwd2_main,'SPM.mat');
end

ss=struct(...
    'swd',['/mindhive/evlab/u/annaiv/TripleEvents/mROI_' parcel '_' ...
    my_loc_task '_' my_loc_contrast '_' my_crit_task '_' date],...   % output directory
    'EffectOfInterest_spm',{spmfiles_main},...                      % first-level SPM.mat files
    'Localizer_spm', {spmfiles_loc},...
    'EffectOfInterest_contrasts',{my_crit_contrast},...    % contrasts of interest
    'Localizer_contrasts',{{my_loc_contrast}},...         % localizer contrast (note: if these contrasts are not orthogonal the toolbox will automatically partition t$
    'Localizer_thr_type','percentile-ROI-level',...
    'Localizer_thr_p',0.1,...                              % specifies percentage OR p-value
    'type','mROI',...                                       % can be 'GcSS' (for automatically defined ROIs), 'mROI' (for manually defined ROIs), or 'voxel' (for voxe$
    'ManualROIs', parcel_file,...
    'overwrite', 1, ...
    'model',1,...                                           % can be 1 (one-sample t-test), 2 (two-sample t-test), or 3 (multiple regression)
    'overlap_thr_roi',0,...
    'ExplicitMasking', '', ...
    'estimation','OLS',...
    'ask','none');                                     % can be 'none' (any missing information is assumed to take default values), 'missing' (any missing informat$
ss=spm_ss_design(ss);                                          % see help spm_ss_design for additional information
ss=spm_ss_estimate(ss);

end

