
date = '20220415';

% setup
addpath(genpath('/om/group/evlab/software/spm12'))
addpath(genpath('/om/group/evlab/software/spm_ss'))
addpath /om/group/evlab/software/conn
conn_module el init

% specify params
my_contrast1 = 'Sent_Sem-Perc';
my_contrast2 = 'Pic_Sem-Perc';

parcel_filepath ='/home/annaiv/annaiv/TripleEvents/GSS_EventsAll/Sent_Sem-Perc_Pic_Sem-Perc_n30_20220415/';
parcel_file = fullfile(parcel_filepath, 'fROIs_filtered_overlap60_minsize200.nii');   

experiments=struct(...
    'name','EventsOrig_instrsep_2runs',...% events subjects
    'pwd1','/mindhive/evlab/u/Shared/SUBJECTS',...
    'pwd2','firstlevel_EventsOrig_instrsep_2runs',...
    'data', {{'040_KAN_langevents_01_PL2017',...
    '057_KAN_langevents_02_PL2017',...
    '059_KAN_langevents_04_PL2017',...
    '056_KAN_langevents_05_PL2017',...
    '067_KAN_langevents_06_PL2017',...
    '068_KAN_langevents_07_PL2017',...
    '019_KAN_langevents_08_PL2017',...
    '070_KAN_langevents_11_PL2017',...
    '087_KAN_langevents_12_PL2017',...
    '078_KAN_langevents_13_PL2017',...
    '089_KAN_langevents_15_PL2017',...
    '076_KAN_langevents_16_PL2017' }});
    
spmfiles={};
for nsub=1:length(experiments.data),
    spmfiles{nsub}=fullfile(experiments.pwd1,experiments.data{nsub},experiments.pwd2,'SPM.mat');
end

ss=struct(...
    'swd', ['/home/annaiv/annaiv/TripleEvents/mROI_EventsAllparcels_EventsOrig/' my_contrast1 '_' my_contrast2 '_' date],...         % output directory
    'files_spm',{spmfiles},...                              % first-level SPM.mat files
    'EffectOfInterest_contrasts',{{'Pic_Sem','Pic_Perc','Sent_Sem','Sent_Perc'}},...    % contrasts of interest
    'Localizer_contrasts',{{my_contrast1, my_contrast2}},...         % localizer contrast (note: if these contrasts are not orthogonal the toolbox will automatically partition theses contrasts by sessions and perform cross-validation) 
    'Localizer_thr_type',{{'percentile-ROI-level'}},...
    'Localizer_thr_p',[.1],... 
    'Localizer_conjunction_type', 'max',...
    'type','mROI',...                                       % can be 'GcSS' (for automatically defined ROIs), 'mROI' (for manually defined ROIs), or 'voxel' (for voxel-based analyses)
    'ManualROIs', parcel_file,...
    'overwrite', 1, ...
    'model',1,...                                           % can be 1 (one-sample t-test), 2 (two-sample t-test), or 3 (multiple regression)
    'ExplicitMasking', [], ...    
    'estimation','OLS',...
    'ask','none');                                       % can be 'none' (any missing information is assumed to take default values), 'missing' (any missing information will be asked to the user), 'all' (it will ask for confirmation on each parameter)
ss=spm_ss_design(ss);                                          % see help spm_ss_design for additional information
ss=spm_ss_estimate(ss);