---
title: "EventsOrig behavioral"
author: "Anna Ivanova"
date: "6/25/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

rm(list=ls()) 

library(lmerTest)
library(ggplot2)
library(dplyr)
library(stringr)
```

## Load behavioral data

```{r load data, echo=FALSE}

#custom read function
# item number not included for now
read_data <- function(directory, filename) {
  d = read.delim(paste(directory, filename, sep='/'), sep=',', header=FALSE)
  d = d %>% rename(Condition=V1, Onset=V2, Accuracy=V3, RT=V4) %>%
    mutate(SubjID = substr(filename,10,nchar(filename)-6),
           Run = substr(filename,nchar(filename)-4,nchar(filename)-4))
  return(d)
}

files = list.files(path='../data/behavioral/EventsOrig', pattern="*.csv")
dat = do.call(rbind, lapply(files, function(x) read_data('../data/behavioral/EventsOrig/', x)))


# clean
dat = dat %>%
  filter(Condition!='fixation')%>%
  filter(Run<4) %>%                             # only modeling the first 3 runs
  mutate(Condition = recode(Condition,
                            'sem_photos'='Pic_Sem',
                            'sem_sentences'='Sent_Sem',
                            'percep_photos'='Pic_Perc',
                            'percep_sentences'='Sent_Perc')) %>%
  mutate(Accuracy = recode(Accuracy,
                           'False'='0', 'True'='1', 'None'='0')) 
dat$RT = as.numeric(as.character(dat$RT))
dat$Accuracy = as.numeric(as.character(dat$Accuracy))

# remove participants with low accuracies (<60%) or right-lateralized language
subs_to_filter = c('KAN_langevents_09')   # bad langloc
dat = dat %>%
  filter(!(SubjID %in% subs_to_filter))

# remove trials with no response
dat_RT = dat %>% filter(!is.na(RT))
dat_acc = dat %>% filter(!is.na(RT))
```

## Response Rate

```{r response rate, echo=FALSE}
dat_responserate = dat %>%
  mutate(Responded = ifelse(is.na(RT), 0, 1)) %>%
  group_by(SubjID, Condition) %>%
  summarize(ResponseRate = sum(Responded)/n())

mean_rr = dat_responserate %>%
  group_by(Condition) %>%
  summarize(ResponseRate = mean(ResponseRate))
mean_rr
```

## Reaction Times

```{r RT analysis, echo=FALSE}
dat_sentsem = dat_RT %>% filter(Condition=='Sent_Sem')
cat('Sent Sem RT =', round(mean(dat_sentsem$RT),3), '(SD = ', round(sd(dat_sentsem$RT),3), ')\n')

dat_sentperc = dat_RT %>% filter(Condition=='Sent_Perc')
cat('Sent Perc RT =', round(mean(dat_sentperc$RT),3), '(SD = ', round(sd(dat_sentperc$RT),3), ')\n')

dat_picsem = dat_RT %>% filter(Condition=='Pic_Sem')
cat('Pic Sem RT =', round(mean(dat_picsem$RT),3), '(SD = ', round(sd(dat_picsem$RT),3), ')\n')

dat_picperc = dat_RT %>% filter(Condition=='Pic_Perc')
cat('Pic Perc RT =', round(mean(dat_picperc$RT),3), '(SD = ', round(sd(dat_picperc$RT),3), ')\n')

cat('Overall=', round(mean(dat_RT$RT),3), '(SD = ', round(sd(dat_RT$RT),3), ')\n')
```

```{r RT plot, echo=FALSE}
ggplot(data=dat_RT %>% filter(RT>0))+
    stat_summary(mapping = aes(x = Condition, y = RT), 
               geom = 'col', fun.y = 'mean', color = 'gray',
               show.legend=FALSE)+
    stat_summary(mapping = aes(x = Condition, y = RT), 
               geom = 'errorbar', fun.data = 'mean_se', color = 'black', 
               size = 1, width=0.3) + theme_minimal()
```
```{r lmer model RT, echo=FALSE}
dat_RT = dat_RT %>%
  mutate(StimType = factor(ifelse(Condition %in% c('Sent_Sem', 'Sent_Perc'), 'Sent', 'Pic'),
         levels=c('Pic', 'Sent'))) %>%
  mutate(Task = factor(ifelse(Condition %in% c('Sent_Sem', 'Pic_Sem'), 'Sem', 'Perc'),
         levels=c('Perc', 'Sem')))

contrasts(dat_RT$StimType) = c(-0.5, 0.5)
contrasts(dat_RT$Task) = c(-0.5, 0.5)
colnames(attr(dat_RT$StimType, "contrasts")) = "Sent>Pic"
colnames(attr(dat_RT$Task, "contrasts")) = "Sem>Perc"

m = lmer(RT ~ StimType*Task + (1|SubjID), data=dat_RT, REML=FALSE)
summary(m)
```


## Accuracies

```{r accuracy analysis, echo=FALSE}
dat_sentsem = dat_acc %>% filter(Condition=='Sent_Sem')
cat('Sent Sem Accuracy =', round(mean(dat_sentsem$Accuracy),3), '(SD = ', round(sd(dat_sentsem$Accuracy),3), ')\n')

dat_sentperc = dat_acc %>% filter(Condition=='Sent_Perc')
cat('Sent Perc Accuracy =', round(mean(dat_sentperc$Accuracy),3), '(SD = ', round(sd(dat_sentperc$Accuracy),3), ')\n')

dat_picsem = dat_acc %>% filter(Condition=='Pic_Sem')
cat('Pic Sem Accuracy =', round(mean(dat_picsem$Accuracy),3), '(SD = ', round(sd(dat_picsem$Accuracy),3), ')\n')

dat_picperc = dat_acc %>% filter(Condition=='Pic_Perc')
cat('Pic Perc Accuracy =', round(mean(dat_picperc$Accuracy),3), '(SD = ', round(sd(dat_picperc$Accuracy),3), ')\n')

cat('Overall Accuracy=', mean(dat_acc$Accuracy), '\n')
```

```{r acc by person, echo=FALSE}
acc_by_person = dat_acc %>% group_by(SubjID) %>%
  summarize(Accuracy=mean(Accuracy))
```

```{r lmer model accuracy, echo=FALSE}
dat_acc = dat_acc %>%
  mutate(StimType = factor(ifelse(Condition %in% c('Sent_Sem', 'Sent_Perc'), 'Sent', 'Pic'),
         levels=c('Pic', 'Sent'))) %>%
  mutate(Task = factor(ifelse(Condition %in% c('Sent_Sem', 'Pic_Sem'), 'Sem', 'Perc'),
         levels=c('Perc', 'Sem')))
contrasts(dat_acc$StimType) = c(-0.5, 0.5)
contrasts(dat_acc$Task) = c(-0.5, 0.5)
colnames(attr(dat_acc$StimType, "contrasts")) = "Sent>Pic"
colnames(attr(dat_acc$Task, "contrasts")) = "Sem>Perc"

contrasts(dat_acc$StimType) = c(-0.5, 0.5)
contrasts(dat_acc$Task) = c(-0.5, 0.5)

m = glmer(Accuracy ~ StimType*Task + (1|SubjID), data=dat_acc, family='binomial')
summary(m)
```

```{r acc plot, echo=FALSE}
ggplot(data=dat_acc)+
    stat_summary(mapping = aes(x = Condition, y = Accuracy), 
               geom = 'col', fun.y = 'mean', color = 'gray',
               show.legend=FALSE)+
    stat_summary(mapping = aes(x = Condition, y = Accuracy), 
               geom = 'errorbar', fun.data = 'mean_se', color = 'black', 
               size = 1, width=0.3) + theme_minimal()
```
