%% ADD PATH
addpath(genpath('~/Documents/spm12'))
addpath(genpath('~/Documents/spm_ss'))


%% ss config
ss = struct( ...
    'swd', './output', ...
    'EffectOfInterest_spm', {{'/Users/ruimingao/Documents/TripleEvents/TripleEvents_firstlevel_spm/040_EventsOrig/SPM.mat'}}, ...
    'Localizer_spm', {{'/Users/ruimingao/Documents/TripleEvents/TripleEvents_firstlevel_spm/040_EventsOrig/SPM.mat'}}, ...
    'EffectOfInterest_contrasts', {{'Perc_sentminusSem_sent', 'Perc_photominusSem_photo'}}, ...
    'Localizer_contrasts', {{'Perc_sentminusSem_sent', 'Perc_photominusSem_photo'}}, ...
    'Localizer_thr_type', {{'percentile-ROI-level'}}, ...
    'Localizer_thr_p', [0.1], ...
    'type', 'GCSS', ...
    'ManualROIs', '/Users/ruimingao/Documents/TripleEvents/TripleEvents/new_parcels/fROIs_filtered_overlap60_minsize200_relabeled.nii', ...
    'overwrite', 1, ...
    'model', 1, ...
    'ExplicitMasking', '', ...
    'estimation', 'OLS', ...
    'ask', 'none', ...
    'Localizer_conjunction_type', 'max' ...
);


%%
% ss=spm_ss_design(ss);       


%%
ss=spm_ss_estimate(ss);