%% ADD PATH
addpath(genpath('~/Documents/spm12'))
addpath(genpath('~/Documents/spm_ss'))


%% ss config
ss = struct( ...
    'swd', './output', ...
    'EffectOfInterest1_spm', {{'/Users/ruimingao/Documents/TripleEvents/TripleEvents_firstlevel_spm/040_EventsOrig/SPM.mat'}}, ...
    'EffectOfInterest2_spm', {{'/Users/ruimingao/Documents/TripleEvents/TripleEvents_firstlevel_spm/040_EventsOrig/SPM.mat'}}, ...
    'EffectOfInterest1_contrasts', {{'Sem_photo'}}, ...
    'EffectOfInterest2_contrasts', {{'Perc_sentminusSem_sent'}}, ...
    'type', 'mROI', ...
    'ManualROIs', '/Users/ruimingao/Documents/TripleEvents/TripleEvents/new_parcels/fROIs_filtered_overlap60_minsize200_relabeled.nii', ...
    'overwrite', 1, ...
    'model', 1, ...
    'ExplicitMasking', '', ...
    'estimation', 'OLS', ...
    'ask', 'none', ...
    'Localizer_conjunction_type', 'max' ...
);


%%
ss=spm_bcc_design(ss);       


%%
ss =spm_bcc_estimate(ss);