
filename = 'spm_ss_mROI_data.csv';
date = '20250521';
rootpath = '../../TripleEvents_data';
basename = 'mROI_';
output_dir = fullfile(rootpath, 'data', 'results_mROI');
if ~exist(output_dir, 'dir')
    mkdir(output_dir)
end

networks = {'language', 'MD', 'DMN', ...
'events_parcels-original_contrast-both', 'events_parcels-flipped_contrast-both', ...
'events_parcels-original_contrast-pic', 'events_parcels-flipped_contrast-pic', ...
'events_parcels-original_contrast-sent', 'events_parcels-flipped_contrast-sent', ...
'events_parcels-LATL-inferior-pole', 'events_parcels-RATL-inferior-pole', ...
'events_parcels-LATL-inferior-pole-mid', 'events_parcels-RATL-inferior-pole-mid'};
network_loc_tasks = {...
    {'SWNlocIPS168_3runs', 'langlocSN'},...
    {'spatialFIN'}, {'spatialFIN'},...
    {'EventsRev_instrsep', 'events2move_instrsep', 'EventsOrig_instrsep_2runs'},...
    {'EventsRev_instrsep', 'events2move_instrsep', 'EventsOrig_instrsep_2runs'},...
    {'EventsRev_instrsep', 'events2move_instrsep', 'EventsOrig_instrsep_2runs'},...
    {'EventsRev_instrsep', 'events2move_instrsep', 'EventsOrig_instrsep_2runs'},...
    {'EventsRev_instrsep', 'events2move_instrsep', 'EventsOrig_instrsep_2runs'},...
    {'EventsRev_instrsep', 'events2move_instrsep', 'EventsOrig_instrsep_2runs'},...
    {'EventsRev_instrsep', 'events2move_instrsep', 'EventsOrig_instrsep_2runs'},...
    {'EventsRev_instrsep', 'events2move_instrsep', 'EventsOrig_instrsep_2runs'},...
    {'EventsRev_instrsep', 'events2move_instrsep', 'EventsOrig_instrsep_2runs'},...
    {'EventsRev_instrsep', 'events2move_instrsep', 'EventsOrig_instrsep_2runs'}};
main_tasks = {'spatialFIN', 'SWNlocIPS168_3runs', 'langlocSN', ...
    'EventsOrig_instrsep_2runs', 'events2move_instrsep', 'EventsRev_instrsep',...
    'Categorization', 'Categorization_v2', 'Categorization_semperc'};

for i=1:length(networks)
    network = networks{i};
    loc_tasks = network_loc_tasks{i};
    for j=1:length(loc_tasks)
        loc_task = loc_tasks{j};
        for k=1:length(main_tasks)
            main_task = main_tasks{k};
            target_dir = fullfile(rootpath, [basename network], [loc_task '_' main_task '_' date]);
            if exist(target_dir, 'dir')
                copyfile(fullfile(target_dir,  filename),...
                 fullfile(output_dir, [network '_' loc_task '_' main_task '.csv']));
            end
        end
    end
end
