---
title: "R overlap"
output: html_notebook
---

# Setup

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

rm(list=ls()) 
library(ggplot2)
library(dplyr)
```

## Plotting settings 

```{r plot settings, include=FALSE}
plot_width = 16
plot_height_2expt = 8
plot_height_3expt = 12

legend_size = 12
axis_title_size = 12
title_size = 14
axis_text_size = 10
facet_label_size = 12
```

# Get data

Quick and dirty first pass 
- subject IDs not recorded
- NAs removed manually

```{r}
# decide which network to test
network = "DMN"
system_pattern = paste("*",network,"*",sep="")

# read
files1 = list.files(path='../data/overlap/overlap_EventsOrig/', pattern=system_pattern)
dat1 = do.call(rbind, lapply(files1, function(x) read.csv(paste('../data/overlap/overlap_EventsOrig/', x, sep=''))))

files2 = list.files(path='../data/overlap/overlap_Events2move/', pattern=system_pattern)
dat2 = do.call(rbind, lapply(files2, function(x) read.csv(paste('../data/overlap/overlap_Events2move/', x, sep=''))))

files3 = list.files(path='../data/overlap/overlap_EventsRev/', pattern=system_pattern)
dat3 = do.call(rbind, lapply(files3, function(x) read.csv(paste('../data/overlap/overlap_EventsRev/', x, sep=''))))

# combine
dat1$Experiment = 'EventsOrig'
dat2$Experiment = 'Events2move'
dat3$Experiment = 'EventsRev'

if (network %in% c("MD", "DMN")) {
  dat = rbind(dat2, dat3)
} else {
  dat = rbind(dat1, dat2, dat3)
}

# manual NA removal
dat = dat %>% filter(!is.na(ROI1))

# clean ROI names
if (network=="lang") {
  dat = dat %>%
      mutate(ROI1 = recode(dat$ROI1,
          '1'='LIFG_orb', '2'='LIFG', '3'='LMFG',
          '4'='LAntTemp', '5'='LPostTemp', '6'='LAngG',
          '7'='RIFG_orb', '8'='RIFG', '9'='RMFG',
          '10'='RAntTemp', '11'='RPostTemp', '12'='RAngG'))
  dat$ROI1 = factor(dat$ROI1, levels=c('LIFG_orb', 'LIFG', 'LMFG', 'LAntTemp', 'LPostTemp', 'LAngG',
                                     'RIFG_orb', 'RIFG', 'RMFG','RAntTemp', 'RPostTemp', 'RAngG'))
} else if (network=="MD") {
  dat = dat %>% 
      mutate(ROI1 = recode(ROI1, 
                       '1'='postParietal',
                        '2'='midParietal',
                        '3'='antParietal',
                        '4'='supFrontal',
                        '5'='precentral_A',
                        '6'='precentral_B',
                        '7'='midFrontal',
                        '8'='midFrontalOrb',
                        '9'='insula',
                        '10'='medialFrontal',
                        '11'='postParietal',
                        '12'='midParietal',
                        '13'='antParietal',
                        '14'='supFrontal',
                        '15'='precentral_A',
                        '16'='precentral_B',
                        '17'='midFrontal',
                        '18'='midFrontalOrb',
                        '19'='insula',
                        '20'='medialFrontal'))
} else {
  dat = dat %>%
    mutate(ROI1 = recode(dat$ROI1,
        '1'='LH_FrontalMed', '2'='LH_PostCing', '3'='LH_TPJ',
        '4'='LH_MidCing', '5'='LH_STGorInsula', '6'='LH_AntTemp',
        '7'='RH_FrontalMed', '8'='RH_PostCing', '9'='RH_TPJ',
        '10'='RH_MidCing', '11'='RH_STGorInsula', '12'='RH_AntTemp'))
}
dat$ROI2 = as.factor(dat$ROI2)
```

## Remove fROIs with no overlap
```{r}
dat.summ.ROI = dat %>%
  group_by(ROI1, ROI2) %>% 
  summarize(meanOverlap = mean(Overlap)) %>%
  filter(meanOverlap>0)

dat = dat.summ.ROI %>% left_join(dat)
```

# Plot

```{r}
plot_height = plot_height_3expt
if (network=="lang") {
  angle_size = 0
} else {
  angle_size = 90
}
if (network=="DMN") {
  plot_width = 12
}

ggplot(data=dat)+
  stat_summary(mapping=aes(x=ROI1, y=Overlap, fill=ROI2),
               geom='col', fun.y='mean', color='black', 
               position=position_dodge(preserve = "single"), alpha=0.85)+
  facet_grid(Experiment ~ .)+
  stat_summary(mapping=aes(x=ROI1, y=Overlap, group=ROI2),
               geom='errorbar', fun.data='mean_se', color='black', 
               position=position_dodge(width=0.9, preserve="single"), width=0)+
  geom_hline(yintercept=0, size=0.5)+
  ggtitle(paste("Overlap:", network, "vs. Events"))+
  labs(x=paste(network, "fROIs"), fill="Event fROIs")+
  coord_cartesian(ylim=c(0,0.15))+
  theme_classic()+
  theme(axis.text.x = element_text(size=axis_text_size, angle=angle_size, color='black'), 
        axis.title.y = element_text(size=axis_title_size), 
        axis.text.y = element_text(size=axis_text_size), 
        legend.text = element_text(size=legend_size), 
        strip.text.x = element_text(size=facet_label_size),
        title = element_text(size=title_size, face='bold'))
ggsave(paste("plots/overlap_", network, ".png", sep=""),
      width=plot_width, height=plot_height, units='cm')
```