---
title: "R overlap"
output: html_notebook
---

# Setup

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

rm(list=ls()) 
library(ggplot2)
library(dplyr)
library(stringr)
library(reshape)
library(gplots)
library(patchwork)
```

## Plotting settings 

```{r plot settings, include=FALSE}
plot_height_1row = 8
plot_height_2rows = 12
plot_height_3rows = 16

plot_width = 24

legend_size = 11
axis_title_size = 12
title_size = 14
axis_text_size = 12
facet_label_size = 12

plot_dir = 'Plots/'
```

## fROI labels

```{r}
lang_frois = c('LH_IFG_orb', 'LH_IFG', 'LH_MFG', 'LH_AntTemp', 'LH_PostTemp', 'LH_AngG',
               'RH_IFG_orb', 'RH_IFG', 'RH_MFG','RH_AntTemp', 'RH_PostTemp', 'RH_AngG')
semantic_frois = c('F1','F2','F3','TP1','TP2','TP3','TP4','Cer1','Cer2','O1','O2')
md_frois = c('LH_postParietal','LH_midParietal','LH_antParietal','LH_supFrontal','LH_precentral_A','LH_precentral_B','LH_midFrontal','LH_midFrontalOrb','LH_insula','LH_medialFrontal','RH_postParietal','RH_midParietal','RH_antParietal','RH_supFrontal','RH_precentral_A','RH_precentral_B','RH_midFrontal','RH_midFrontalOrb','RH_insula','RH_medialFrontal')
dmn_frois = c('LH_FrontalMed', 'LH_PostCing', 'LH_TPJ','LH_MidCing', 'LH_STGorInsula', 'LH_AntTempr','RH_FrontalMed', 'RH_PostCing', 'RH_TPJ','RH_MidCing', 'RH_STGorInsula', 'RH_AntTempr')
```

# Supporting functions

## Read data

```{r}
read_datafile <- function(data_path, filename, expt1, expt2) {
  d = read.csv(paste(data_path, filename, sep=''))
  d = d %>% mutate(UID = substr(filename, 1, 3)) 
  return(d)
} 

rename_ROI_col <- function(ROIcol, network) {
  if (network=='language') {
    result = recode(ROIcol,
            '1'='LH_IFG_orb', '2'='LH_IFG', '3'='LH_MFG',
            '4'='LH_AntTemp', '5'='LH_PostTemp', '6'='LH_AngG',
            '7'='RH_IFG_orb', '8'='RH_IFG', '9'='RH_MFG',
            '10'='RH_AntTemp', '11'='RH_PostTemp', '12'='RH_AngG') 
    result = factor(result, levels=lang_frois)
  } else if (network=='MD') {
    result = recode(ROIcol, 
                       '1'='LH_postParietal',
                        '2'='LH_midParietal',
                        '3'='LH_antParietal',
                        '4'='LH_supFrontal',
                        '5'='LH_precentral_A',
                        '6'='LH_precentral_B',
                        '7'='LH_midFrontal',
                        '8'='LH_midFrontalOrb',
                        '9'='LH_insula',
                        '10'='LH_medialFrontal',
                        '11'='RH_postParietal',
                        '12'='RH_midParietal',
                        '13'='RH_antParietal',
                        '14'='RH_supFrontal',
                        '15'='RH_precentral_A',
                        '16'='RH_precentral_B',
                        '17'='RH_midFrontal',
                        '18'='RH_midFrontalOrb',
                        '19'='RH_insula',
                        '20'='RH_medialFrontal') 
  } else if (network=='DMN') {
    result = recode(ROIcol,
        '1'='LH_FrontalMed', '2'='LH_PostCing', '3'='LH_TPJ',
        '4'='LH_MidCing', '5'='LH_STGorInsula', '6'='LH_AntTempr',
        '7'='RH_FrontalMed', '8'='RH_PostCing', '9'='RH_TPJ',
        '10'='RH_MidCing', '11'='RH_STGorInsula', '12'='RH_AntTempr')
  } else if (network=="events") {
    result = recode(ROIcol, 
                    '1'='F2', '2'='F1', '3'='TP3', '4'='TP2', '5'='Cer1', '6'='TP4',
                    '7'='F3', '8'='TP1', '9'='O1', '10'='Cer2', '11'='O2')
    result = factor(result, levels=semantic_frois)
  } else {
    stop(paste('Unknown network:', network))
  }
  return(result)
  
}

# clean ROI names
rename_ROIs <- function(dat, network1, network2) {
  dat = dat %>%
    mutate(ROI1 = rename_ROI_col(dat$ROI1, network1),
           ROI2 = rename_ROI_col(dat$ROI2, network2))
  return(dat)
}
```

# MAIN - events vs other networks

## Get data

```{r}
dfs <- list()
index = 1

expts = c('spatialFIN', 'spatialFIN', 'SWNlocIPS168_3runs', 'langlocSN',
    'EventsOrig_instrsep_2runs', 'events2move_instrsep', 'EventsRev_instrsep')
networks = c('MD', 'DMN', 'language', 'language', 'events', 'events', 'events')
data_path = '../data/results_fROI_overlap/'
for (i in seq_along(expts)) {
  expt1 = expts[i]
  network1 = networks[i]
  for (j in seq_along(expts)) {
    expt2 = expts[j]
    network2 = networks[j]
    file_pattern = paste("*",paste(network1,expt1,network2,expt2,sep="_"),"*",sep="")
    filenames = list.files(path=data_path, pattern=file_pattern)
    if (length(filenames)==0) {
      next
    }
    dat = do.call(rbind, lapply(filenames, function(x) read_datafile(data_path, x)))
    dat = rename_ROIs(dat, network1, network2)
    dat$Network1 = network1
    dat$Experiment1 = expt1
    dat$Network2 = network2
    dat$Experiment2 = expt2
    
    dfs[[index]] <- dat
    index = index+1
  }
}

dat.full = do.call("rbind", dfs)
# manual NA removal
dat.full = dat.full %>% filter(!is.na(ROI1))
```

## Clean
```{r}
# do not look at data comparing different events experiments (yet)
dat = dat.full %>% 
  filter(!(Network1=='events' & Network2=='events' & Experiment1!=Experiment2))

# remove fROIs with no overlap
dat.mean = dat %>%
  group_by(ROI1, ROI2, Network1, Experiment1, Network2, Experiment2) %>% 
  summarize(meanOverlap = mean(Overlap)) %>%
  ungroup()

dat.nonzero = dat.mean %>% filter(meanOverlap>0) %>% left_join(dat)
```

## Plot

```{r}
dat.events = dat.nonzero %>% filter(Network2=='events')

ggplot(data=dat.events)+
  stat_summary(mapping=aes(x=ROI2, y=Overlap, fill=ROI1),
               geom='col', fun='mean', color='black', 
               position=position_dodge(), alpha=0.85)+
  ggforce::facet_row(vars(Network1), scales = 'free_x', space = 'free')+
  ggforce::facet_col(vars(Experiment2))+
  stat_summary(mapping=aes(x=ROI2, y=Overlap, group=ROI1),
               geom='errorbar', fun.data='mean_se', color='black', 
               position=position_dodge(width=0.9), width=0)+
  geom_hline(yintercept=0, size=0.5)+
  theme_classic()+
  theme(axis.text.x = element_text(size=axis_text_size, angle=90, color='black'), 
        axis.title.y = element_text(size=axis_title_size), 
        axis.text.y = element_text(size=axis_text_size), 
        legend.text = element_text(size=legend_size),
        legend.position = 'bottom',
        strip.text.x = element_text(size=facet_label_size),
        title = element_text(size=title_size, face='bold'))
# ggsave(paste("plots/overlap_", network, ".png", sep=""),
#       width=plot_width, height=plot_height, units='cm')
```

```{r}
#dat.wide =  pivot_wider(dat.mean, names_from=c(Network2, ROI2), values_from=meanOverlap)
dat$Network1 = factor(dat$Network1, levels=c('events', 'language', 'MD', 'DMN'))

froi_order = c(unique(substring(lang_frois, 4)), 
               unique(substring(md_frois, 4)),
               unique(substring(dmn_frois, 4)))

d = dat %>% 
  filter(Network2=='events') %>%
  filter(Network1!='events') %>%
  filter(!(startsWith(ROI1, 'R'))) %>%
  mutate(Network1 = recode(Network1, 'events'='')) %>%
  group_by(ROI1, ROI2, Network1, Network2) %>% 
  summarize(meanOverlap = mean(Overlap)) %>%
  ungroup() %>%
  mutate(ROI1 = substring(ROI1,4))
d$ROI1 = factor(d$ROI1, levels=froi_order)
d$ROI2 = factor(d$ROI2, levels=semantic_frois)

ggplot(d)+
  geom_tile(mapping=aes(x=ROI2, y=ROI1, fill=meanOverlap), color="black")+
  scale_y_discrete(limits=rev)+
  labs(x="", y="", fill="Mean\noverlap ")+
  scale_x_discrete(position = "top")+
  theme(legend.position = "bottom",
        axis.text.x = element_text(angle = 90, hjust = 0, vjust=2))+
  coord_fixed()

ggsave(paste(plot_dir, "overlap_heatmap.png", sep=""),
      width=plot_width*0.5, height=14, units='cm')
```

# Different Events Experiments

```{r}
dat.events2events = dat.full %>% 
  filter(Network1=='events' & Network2=='events') %>%
  filter(ROI1==ROI2) %>%
  mutate(ROI=ROI1,
         Experiment1 = recode(Experiment1, 'EventsOrig_instrsep_2runs'='E1', 'events2move_instrsep'='E2', 'EventsRev_instrsep'='E3'),
         Experiment2 = recode(Experiment2, 'EventsOrig_instrsep_2runs'='E1', 'events2move_instrsep'='E2', 'EventsRev_instrsep'='E3'),
         Experiments=paste(Experiment1, Experiment2, sep='/')) %>% 
  select(-ROI1, -ROI2) %>%
  filter(Experiments!='E3/E2')    # duplicate
dat.events2events$Experiments = factor(dat.events2events$Experiments, levels=c('E1/E1', 'E2/E2', 'E3/E3', 'E2/E3'))

ggplot(data=dat.events2events)+
  stat_summary(mapping=aes(x=ROI, y=Overlap, fill=Experiments),
               geom='col', fun='mean', color='black', 
               position=position_dodge(), alpha=0.85)+
  stat_summary(mapping=aes(x=ROI, y=Overlap, group=Experiments),
               geom='errorbar', fun.data='mean_se', color='black', 
               position=position_dodge(width=0.9), width=0)+
  geom_hline(yintercept=0, size=0.5)+
  labs(x=NULL)+
  theme_classic()
ggsave(paste(plot_dir, "overlap_eventsexpts.png", sep=""),
      width=plot_width, height=plot_height_1row, units='cm')
```

# Extra - langloc

```{r}
dat.lang2lang = dat.full %>% 
  filter(Network1=='language' & Network2=='language') %>%
  filter(ROI1==ROI2) %>% mutate(ROI=ROI1) %>% select(-ROI1, -ROI2) %>%
  filter(Experiment1==Experiment2) %>% mutate(Experiment=Experiment1) %>% 
  select(-Experiment1, -Experiment2)

dat.lang2lang.mean = dat.lang2lang %>% 
  group_by(UID, Experiment) %>% 
  summarize(Overlap=mean(Overlap))

p.lang.mean = ggplot(data=dat.lang2lang.mean, mapping=aes(x='Mean', y=Overlap, fill=Experiment))+
  stat_summary(geom='col', fun='mean', color='black', 
               position=position_dodge(), alpha=0.85,
               show.legend = FALSE)+
  stat_summary(geom='errorbar', fun.data='mean_se', color='black', 
               position=position_dodge(width=0.9), width=0)+
  geom_point(shape=21, size=0.5, position=position_jitter(width=0.02),
             show.legend = FALSE)+
  facet_wrap(.~Experiment, nrow=2)+
  geom_hline(yintercept=0, size=0.5)+
  labs(x=NULL)+
  coord_cartesian(ylim=c(0,1))+
  theme_classic()+
  theme(strip.text = element_blank(),
        axis.text.x = element_text(angle=90))


p.lang.roi = ggplot(data=dat.lang2lang, mapping=aes(x=ROI, y=Overlap, fill=Experiment))+
  stat_summary(geom='col', fun='mean', color='black', 
               position=position_dodge(), alpha=0.85)+
  stat_summary(geom='errorbar', fun.data='mean_se', color='black', 
               position=position_dodge(width=0.9), width=0)+
  geom_point(shape=21, size=0.5, position=position_jitter(width=0.02))+
  facet_wrap(.~Experiment, nrow=2)+
  geom_hline(yintercept=0, size=0.5)+
  labs(x=NULL, y=NULL)+
  coord_cartesian(ylim=c(0,1))+
  theme_classic()+
  theme(strip.text = element_blank(),
        axis.text.x = element_text(angle=90))

p.lang.mean + p.lang.roi + plot_layout(widths=c(1,6))
ggsave(paste(plot_dir, 'langloc overlap.png', sep=''),
       width=plot_width, height=plot_height_3rows, units='cm')
```